### ISSUE TITLE
Travis CI not exist?

### ISSUE THREAD

**Issue by PeterDaveHello** [tellform/tellform#164]
Looks like both origin **whitef0x0/tellform** [![Build Status](https://travis-ci.org/whitef0x0/tellform.svg?branch=master)](https://travis-ci.org/whitef0x0/tellform) and current **tellform/tellform** [![Build Status](https://travis-ci.org/tellform/tellform.svg?branch=master)](https://travis-ci.org/tellform/tellform) not exist on Travis CI?

**Comment by whitef0x0** [comment]
@PeterDaveHello Yea it's weird, I can't actually view my tellform organization on travis-ci.org even though I just granted it access. I'll email Travis-CI and see what's up.

**Comment by whitef0x0** [comment]
@PeterDaveHello this has been fixed.
