### ISSUE TITLE
We are unable to implement the forms

### ISSUE THREAD

**Issue by jyothimanchena** [tellform/tellform#165]
Hi ,

we are  tried to implement the below forms, this type of forms we are unable to implement in your tellform platform , please help how to implement this type of forms in your platform .please check the below sample form links.
sample form link : https://www.saddleback.edu/uploads/admissions/documents/creditbyexamform.pdf
                             
        https://www.saddleback.edu/uploads/admissions/documents/ab540_ab2000_form_07012015.pdf

Thanks
Jyothi

**Comment by whitef0x0** [comment]
Not sure I can really help you with this. Seems like a feature request and not a bug. 

If you need support /custom solutions I do offer contracting.
