### ISSUE TITLE
BUG: Can't Delete Questions

### ISSUE THREAD

**Issue by datdudejibril** [tellform/tellform#172]
#### What's this issue about?

I can't delete a created question.  There's no delete button.   See screen shot
http://prntscr.com/f57qkv

#### Expected behavior

Display a delete button

#### Actual behavior

No button was displayed

#### Steps to reproduce

Login to form with questions

#### Environment

Chrome and Firefox

2angular.js:12783 TypeError: Cannot read property 'form_fields' of null
    at transformResponse (application.min.js:4)
    at ed (angular.js:9790)
    at c (angular.js:10582)
    at angular.js:15097
    at n.$eval (angular.js:16359)
    at n.$digest (angular.js:16175)
    at n.$apply (angular.js:16467)
    at g (angular.js:10852)
    at S (angular.js:11050)
    at XMLHttpRequest.e (angular.js:11001)
(anonymous) @ angular.js:12783
(anonymous) @ angular.js:9535
(anonymous) @ angular.js:15105
$eval @ angular.js:16359
$digest @ angular.js:16175
$apply @ angular.js:16467
g @ angular.js:10852
S @ angular.js:11050
e @ angular.js:11001
Navigated to https://admin.tellform.com/
admin.tellform.com/:55 GET https://admin.tellform.com/static//lib/jquery-ui/themes/flick/jquery-ui.mdcss 
admin.tellform.com/:55 GET https://admin.tellform.com/static//lib/jquery-ui/themes/flick/jquery-ui.mdcss 
angular.js:12783 ui.sortable: ngModel not provided! [div.panel-group.dropzone.ng-isolate-scope]
2angular.js:12783 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.4.10/ngRepeat/dupes?p0=field%20in%20myform.fo…%2C%22isSubmission%22%3Afalse%2C%22%24%24hashKey%22%3A%22object%3A70%22%7D
    at angular.js:38
    at angular.js:28030
    at angular.js:16066
    at n.$digest (angular.js:16203)
    at n.$apply (angular.js:16467)
    at g (angular.js:10852)
    at S (angular.js:11050)
    at XMLHttpRequest.t.onload (angular.js:10991)
    at XMLHttpRequest.c (raven.js:337)
(anonymous) @ angular.js:12783
(anonymous) @ angular.js:9535
$digest @ angular.js:16221
$apply @ angular.js:16467
g @ angular.js:10852
S @ angular.js:11050
t.onload @ angular.js:10991
c @ raven.js:337
angular.js:12783 dropdown-toggle is now deprecated. Use uib-dropdown-toggle instead.
(anonymous) @ angular.js:12783
link @ ui-bootstrap-tpls.min.js:9
ea @ angular.js:9079
w @ angular.js:8566
g @ angular.js:7965
w @ angular.js:8561
g @ angular.js:7965
w @ angular.js:8561
g @ angular.js:7965
w @ angular.js:8561
g @ angular.js:7965
g @ angular.js:7968
w @ angular.js:8561
g @ angular.js:7965
(anonymous) @ angular.js:7845
link @ angular.js:24916
ea @ angular.js:9079
w @ angular.js:8566
g @ angular.js:7965
(anonymous) @ angular.js:7845
(anonymous) @ angular.js:7983
k @ angular.js:8593
(anonymous) @ angular.js:24862
(anonymous) @ angular.js:15097
$eval @ angular.js:16359
$digest @ angular.js:16175
$apply @ angular.js:16467
g @ angular.js:10852
S @ angular.js:11050
t.onload @ angular.js:10991
c @ raven.js:337
angular.js:12783 collapse is now deprecated. Use uib-collapse instead.
(anonymous) @ angular.js:12783
link @ ui-bootstrap-tpls.min.js:8
ea @ angular.js:9079
w @ angular.js:8566
g @ angular.js:7965
g @ angular.js:7968
w @ angular.js:8561
g @ angular.js:7965
(anonymous) @ angular.js:7845
link @ angular.js:24916
ea @ angular.js:9079
w @ angular.js:8566
g @ angular.js:7965
(anonymous) @ angular.js:7845
(anonymous) @ angular.js:7983
k @ angular.js:8593
(anonymous) @ angular.js:24862
(anonymous) @ angular.js:15097
$eval @ angular.js:16359
$digest @ angular.js:16175
$apply @ angular.js:16467
g @ angular.js:10852
S @ angular.js:11050
t.onload @ angular.js:10991
c @ raven.js:337
(index):55 GET https://admin.tellform.com/static//lib/jquery-ui/themes/flick/jquery-ui.mdcss 
application.min.js:4 n {$id: 37, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 49, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 54, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 59, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 64, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 69, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 94, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 119, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 124, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 134, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 144, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 154, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
application.min.js:4 n {$id: 159, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null…}
socket.io-1.4.5.js:1 WebSocket connection to 'wss://admin.tellform.com/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 502
WS.doOpen @ socket.io-1.4.5.js:1
Transport.open @ socket.io-1.4.5.js:1
Socket.open @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Manager.open.Manager.connect @ socket.io-1.4.5.js:2
Manager @ socket.io-1.4.5.js:2
Manager @ socket.io-1.4.5.js:2
lookup @ socket.io-1.4.5.js:2
c @ application.min.js:4
a @ application.min.js:4
e @ angular.js:4560
(anonymous) @ angular.js:4412
e @ angular.js:4560
(anonymous) @ angular.js:4377
d @ angular.js:4519
e @ angular.js:4551
(anonymous) @ angular.js:4412
e @ angular.js:4560
(anonymous) @ angular.js:4377
d @ angular.js:4519
e @ angular.js:4551
(anonymous) @ angular.js:7359
p @ angular.js:341
(anonymous) @ angular.js:7357
e @ angular.js:4560
(anonymous) @ angular.js:4412
e @ angular.js:4560
(anonymous) @ angular.js:4377
d @ angular.js:4519
Q @ angular.js:8629
ja @ angular.js:8012
X @ angular.js:7884
X @ angular.js:7900
J @ angular.js:7787
(anonymous) @ angular-ui-router.min.js:7
ea @ angular.js:9079
w @ angular.js:8566
g @ angular.js:7965
(anonymous) @ angular.js:7845
k @ angular-ui-router.min.js:7
(anonymous) @ angular-ui-router.min.js:7
$broadcast @ angular.js:16682
y.transition.J.then.y.transition.y.transition @ angular-ui-router.min.js:7
(anonymous) @ angular.js:15097
$eval @ angular.js:16359
$digest @ angular.js:16175
$apply @ angular.js:16467
g @ angular.js:10852
S @ angular.js:11050
t.onload @ angular.js:10991
c @ raven.js:337
4socket.io-1.4.5.js:1 WebSocket connection to 'wss://admin.tellform.com/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 502
WS.doOpen @ socket.io-1.4.5.js:1
Transport.open @ socket.io-1.4.5.js:1
Socket.open @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Manager.open.Manager.connect @ socket.io-1.4.5.js:2
(anonymous) @ socket.io-1.4.5.js:3
c @ raven.js:337

**Comment by whitef0x0** [comment]
What is your screen resolution?
