### ISSUE TITLE
Feature Request - Multilingual support

### ISSUE THREAD

**Issue by ajmas** [tellform/tellform#173]
#### What's this issue about?

Feature request to add multi-lingual support.

#### About the Feature

It would be useful to have multi-lingual support in the forms, such that when the form is displayed it displays in the user's language and possibly offers links to alternative languages, for which translations have been provided.

During entering I am thinking:

- Top of form allows to specify which languages will be included
- Each question can have a translation added. Maybe in the same way as Facebook (see image)?

![facebook-new-post](https://cloud.githubusercontent.com/assets/682269/25824587/f679a2cc-340d-11e7-840c-daf3fcf40a72.png)

**Comment by whitef0x0** [comment]
We do already have multilingual forms, but they aren't translated on the fly and arr limited to German, English Français and Español.
