### ISSUE TITLE
Docker run issue

### ISSUE THREAD

**Issue by TheFonix** [tellform/tellform#174]
#### What's this issue about?
Cant access web GUI once ive ran the docker run command docker run -d -p 80:80 --name tellform tellform/development I changed 3000 to 80 for the port of course

#### Expected behavior
I would be able to access the web GUI

#### Actual behavior
Cant Connect to the web GUI

#### Steps to reproduce
docker run command docker run -d -p 80:80 --name tellform tellform/development

#### Environment
Ubuntu 16.04, Docker version 17.05.0-ce, build 89658be

**Comment by DigNZ** [comment]
I've tried Docker and Heroku and installing dependencies and running it directly and none of those deployment options work at the moment as far as I can tell.

**Comment by TheFonix** [comment]
Glad its not just me!

**Comment by jkooper** [comment]
Would love to get it running as well for a uni project

**Comment by achedeuzot** [comment]
@TheFonix You need to start a redis & mongodb server and link them to tellform. Because I guess currently tellform can't start without those services.

**Comment by jkooper** [comment]
@achedeuzot If you mean this: [Deploy with Docker](https://github.com/tellform/tellform#deploying-with-docker) doesn't work as well

**Comment by achedeuzot** [comment]
@jkooper You can try what I did in my ticket: https://github.com/tellform/tellform/issues/175

    $ docker run -p 27017:27017 -d --name some-mongo mongo
    $ docker run -p 127.0.0.1:6379:6379 -d --name some-redis redis
    $ docker run --rm -p 3000:3000 --link some-redis:redis-db --link some-mongo:db -e MAILER_EMAIL_ID='mailer_username' -p 80:80 tellform/development

**Comment by TheFonix** [comment]
That seems to work!

**Comment by jkooper** [comment]
Awesome, this works. Thanks @achedeuzot

**Comment by TheFonix** [comment]
I feel like this software is just overall broken :/ or at least anything surrounding the docker container is ..

**Comment by whitef0x0** [comment]
@TheFonix sorry to hear that. I'll try to get the documentation and everything up to date in a few weeks time.

**Comment by h133gqa** [comment]
I followed the the documentation but ended here: docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"-e\": executable file not found in $PATH".

**Comment by whitef0x0** [comment]
@h133gqa I've updated the documentation and tested it on my local machine and it seems to be working now for the docker installation.
