### ISSUE TITLE
Can't login/signup to the app with infinite loop

### ISSUE THREAD

**Issue by achedeuzot** [tellform/tellform#175]
#### What's this issue about?
I tried running it on my local machine with docker and couldn't use the app easily. I had to find the verification token in mongodb through the CLI and paste it into the interface.
Once I was logged in, there is an infinite loop/redirection between /forms and /signing. I tried it on Google Chrome and Firefox with the same behavior.

#### Expected behavior
I hoped to easily start tellform to try it out. It was complicated and after much efforts still couldn't make it work. I'm sad :[

#### Actual behavior & Steps to reproduce
First I tried the one-liner published on the tellform.com website:
`docker run -d -p 3000:3000 --name tellform tellform/development`
It does not work because there need to be a redis & mongodb server running.

So next I tried with the procedure on the github repository:

    $ docker run -p 27017:27017 -d --name some-mongo mongo
    $ docker run -p 127.0.0.1:6379:6379 -d --name some-redis redis
    $ docker run --rm -p 3000:3000 --link some-redis:redis-db --link some-mongo:db tellform/development -e MAILER_EMAIL_ID='mailer_username'  -p 80:80

But the last command is wrong, it should be `$ docker run --rm -p 3000:3000 --link some-redis:redis-db --link some-mongo:db -e MAILER_EMAIL_ID='mailer_username' -p 80:80 tellform/development`.

I managed it to make it run and could see the signin form at `http://127.0.0.1:3000`. I signed up but I couldn't activate my account so I couldn't log in. I had to `docker exec` into the mongodb to search for the temporary_users and get the activation code.

After that, I was finally able to log into the admin interface but it went into an infinite loop between `/signin` and `/forms` so I couldn't click on anything. In Chrome the tab became unresponsive so I cancelled it. In Firefox, the whole browser froze so I had to kill it.
 
#### Environment
I'm on a MacBook Pro with:

- Mac OS Sierra 10.12.5
- Chrome 58.0.3029.110 (64-bit)
- Firefox 53.0.3 (64-bit)
- docker version:
    Client:
     Version:      17.03.1-ce
     API version:  1.27
     Go version:   go1.7.5
     Git commit:   c6d412e
     Built:        Tue Mar 28 00:40:02 2017
     OS/Arch:      darwin/amd64

    Server:
     Version:      17.03.1-ce
     API version:  1.27 (minimum version 1.12)
     Go version:   go1.7.5
     Git commit:   c6d412e
     Built:        Fri Mar 24 00:00:50 2017
     OS/Arch:      linux/amd64
     Experimental: true

I had high hopes of using tellform but currently the website tellform.com demo area is out of order and there is no way to test it on my machine easily. This makes me sad :(

**Comment by fxlemire** [comment]
Thanks for that last `docker run` command, that fixed it for me :)

To sign in you simply had to replace the `tellform.dev` part of the confirmation link by your local url, in your case `127.0.0.1:3000`

I'm also stuck on that infinite loop problem between `/signin` and `/forms`

If you look at the console, `/forms` shoots a 401 error. I'm guessing it incorrectly assumes that we don't have the right to be there, so logs us out, then we get an automatic login on `/signin`, etc.

**Comment by DrakeWitt** [comment]
The solution I found was to just not run it inside a docker container, and manually set it up the other way Kinda sucks that the docker container is broken but oh well. The framework the project is built on (MeanJS) is buggy and I've had headaches dealing with it on other projects.

**Comment by iit2011081** [comment]
I'm also facing the same issue but I'm not using docker. I changed my .env file and do grunt build still it is taking old environment variables.

**Comment by whitef0x0** [comment]
@achedeuzot @fxlemire @DrakeWitt @iit2011081  sadly currently I am not able to fix things as I've been swamped with work in the past few weeks. However I'll try to get to your issues by next weekend.

**Comment by whitef0x0** [comment]
@achedeuzot @fxlemire @DrakeWitt @iit2011081 I've updated the docker instructions and tested in on my local machine. If you have any other problems, let me know.
