### ISSUE TITLE
Heroku deploy, SparkPost has no free tier.

### ISSUE THREAD

**Issue by rhuang** [tellform/tellform#177]
#### What's this issue about?
When I try to deploy to Heroku (https://elements.heroku.com/buttons/whitef0x0/tellform), I get the following error: `The plan "undefined" for the addon "sparkpost" does not exist. Please ensure that the plan is spelled correctly.` It appears Sparkpost has no free tier anymore.

#### Expected behavior
I expected Heroku deploy to work with SparkPost having a free tier.

#### Actual behavior
Seems like SparkPost can't find a free tier plan.

#### Steps to reproduce
Click on `Deploy to Heroku`

#### Environment
N/A

**Comment by treed593** [comment]
+1 👍

**Comment by whitef0x0** [comment]
@rhuang I'll try to get this by next weekend.

**Comment by whitef0x0** [comment]
This has been fixed by moving to SendGrid for the Heroku Deploy Button.
