### ISSUE TITLE
"Get started" button leads to impossible signup

### ISSUE THREAD

**Issue by seikonfertrad** [tellform/tellform#191]
#### What's this issue about?

Whenever I click "Get Started", it takes me to the page "https://admin.tellform.com/#!/signup" where a header tells me "Retry for a live version - This page (https://admin.tellform.com/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert". As a result, the signup doesn't work.

#### Expected behavior

I want to sign up.
#### Actual behavior

Nothing, it simply is unresponsive.
#### Steps to reproduce

Go to tellform.com, click Get Started button.
#### Environment

OS X El Capitan
Version 10.11.6 (15G1510)
On a MacBook Pro (13-inch, Mid 2009)

**Comment by jhnsntmthy** [comment]
Me too. Heroku doesnt work

**Comment by whodafly** [comment]
Trying to sign up, doesn't work. Same symptoms.

**Comment by whitef0x0** [comment]
@whodafly @jhnsntmthy @seikonfertrad sadly currently I am not able to fix things as I've been swamped with work. I'll try to get to in next weekend

**Comment by whitef0x0** [comment]
This has been fixed
