### ISSUE TITLE
Front page and examples give a 502 Bad Gateway

### ISSUE THREAD

**Issue by nikhita** [tellform/tellform#193]
#### What's this issue about?

- https://tellform.com/ shows a 502 Bad Gateway.
- Clicking on any of the examples here - https://tellform.com/examples - gives a 502 too.

#### Expected behavior

Should load the website properly, not give a 502.

#### Actual behavior

Gives a 502.

#### Steps to reproduce

Visit the links mentioned.

#### Environment

from `cat /etc/os-release`:
I'm on Ubuntu 14.04.4 LTS (Trusty Tahr).

Linux kernel version from `uname -a`:
4.2.0-34-generic

**Comment by OisinOskar** [comment]
Also broken for me.

**Comment by robwent** [comment]
I just came here to check if the project was dead after visiting the website and seeing broken images, missing ssl certs on example links etc.

I was very surprised to see this much activity on github. Many people may decide not to use the software after visiting the website as it looks abandoned.

**Comment by whitef0x0** [comment]
@robwent it's still active, but sadly currently I am not able to update the server as I've been swamped with work. I'll try to get to in next weekend

**Comment by xperiencereal** [comment]
today it's also broken down....

**Comment by nebaon** [comment]
Is there any news here, @whitef0x0 ? Site is down for me too. Hope still project is still alive, has a lot of potential.
