### ISSUE TITLE
Template views Translations

### ISSUE THREAD

**Issue by josx** [tellform/tellform#194]
#### What's this issue about?
Some strings in templates are not usiing translation filters. 

#### Expected behavior
Those strings must be in i18n files.

#### Actual behavior
Some Strings are hardcoded on templates.

We must replace all template ```strings``` with ```{{ 'strings' | translate }}``` and then update all i18n files with those strings and proper translations

At least i have seen several strings like "Form Paused", "responses", "Edit your profile" and more

**Comment by whitef0x0** [comment]
@josx can you get to this yourself?

**Comment by josx** [comment]
Sure! @leo-orellana from our team will do a PR on this.
