### ISSUE TITLE
Translations on controllers and services

### ISSUE THREAD

**Issue by leo-orellana** [tellform/tellform#196]
#### What's this issue about?
Some strings in controllers are not usiing translation filters.

#### Expected behavior
Those strings must be in i18n files.

#### Actual behavior
Some Strings are hardcoded on controllers and services.

**Comment by whitef0x0** [comment]
Closing this as I've merged the PR.

**Comment by josx** [comment]
@whitef0x0 There are more strings we need to translate on services (like radiobuttons, input text, etc).

**Comment by whitef0x0** [comment]
@josx my bad. I didn't look through it carefully enough

**Comment by whitef0x0** [comment]
@josx any update on your teams progress on this?

**Comment by josx** [comment]
i was a week out on vacations, today i will give you an update on advance

**Comment by whitef0x0** [comment]
@josx cool. If you have any questions or anything don't hesitate to drop me an email (which you can find in my profile).
