### ISSUE TITLE
Translations on backend

### ISSUE THREAD

**Issue by leo-orellana** [tellform/tellform#197]
#### What's this issue about?
Some strings in backend are not usiing translation filters.

#### Expected behavior
Those strings must be in i18n files.

#### Actual behavior
Some Strings are hardcoded on backend.
Ex: 
message = 'Something went wrong';
res.status(200).send('Form submission successfully saved');

**Comment by josx** [comment]
I will open this issue, becasue on frontend we show several string, from backend. An the backend still no have any library to translate string. Some one on our team https://github.com/Cambalab/ will be doing this.

**Comment by whitef0x0** [comment]
@josx you can translate on the backend as well. I'll try to find an example for you.

**Comment by whitef0x0** [comment]
@josx can I close this now?

**Comment by josx** [comment]
just give me one more week, i will take a look on the code to be sure about strings that need to be translated (if there are, i will do the translatation).

**Comment by whitef0x0** [comment]
@josx might be worth looking into adding a linter or something to check untranslated strings. I'll look around tmrw and see if there's any easy way to do this.

**Comment by whitef0x0** [comment]
@josx any updates?

**Comment by josx** [comment]
Sorry but i am busy right now, if you want close it by now.

**Comment by whitef0x0** [comment]
This has been fixed and completed in the 2.20 release.
