### ISSUE TITLE
View forms broken

### ISSUE THREAD

**Issue by leonardloo** [tellform/tellform#204]
View forms seem to be broken. The examples on tellform.com work once in a while, but the self-hosted Tellform (Docker) does not work. I get a 401 error whenever I view forms.

May I ask what's going on?

**Comment by whitef0x0** [comment]
@leonardloo Sorry I was in the middle of maintenance on tellform.com which is why they weren't working 100% of the time.

What url/domain are you trying to access your self-hosted instance from? The 401 error occurs whenever the cookie domain (i.e. BASE_URL) does not match the domain you are trying to access from.

**Comment by leonardloo** [comment]
I'm hosting on localhost:3000. I ran it using docker instructions provided on tellform's README. When I created a form it's sharable url has the username as a subdomain, i.e. leonardloo.localhost:3000/#!/forms/<form_id> which results in a 401. 

When I removed the subdomain and changed it to localhost:3000, this error went away. How do I fix this?

**Comment by leonardloo** [comment]
Another question: Why do I have to provide MAILER credentials? What are we using MAILER here for? When I ran the docker command as it is without filling in MAILER credentials, tellforms still managed to run locally with no issues. Why is that so?

**Comment by whitef0x0** [comment]
@leonardloo MAILER credentials are necessary if you want others to be able to signup

**Comment by whitef0x0** [comment]
@leonardloo If you run this "docker run --rm -p 3000:3000 --link some-redis:redis-db --link some-mongo:db -e "SUBDOMAINS_DISABLED=TRUE" -e "DISABLE_CLUSTER_MODE=TRUE" -e "MAILER_EMAIL_ID=<YourEmailAPI_ID>" -e "MAILER_FROM=<noreply@yourdomain.com>" -e "MAILER_SERVICE_PROVIDER=<YourEmailAPIProvider>"  -e "MAILER_PASSWORD=<YourAPIKey>" -e "BASE_URL=localhost" -p 80:80 tellform/development" it will work with a localhost domain

**Comment by whitef0x0** [comment]
Currently custom subdomains per user don't work with localhost as you need an actual domain. Forgot to add that to the docker instructions. Sorry about that!

**Comment by leonardloo** [comment]
No problem. Thanks!

**Comment by leonardloo** [comment]
So now when I cloned the repo, built it locally with the Dockerfile, `docker build -t tellform -f ./Dockerfile .` and ran it `docker run -it tellform` I am getting the following error:

```
Error: listen EADDRINUSE :::20523
```

I already did a `pkill node` and there are no processes running on 20523. Why is this happening?

**Comment by josx** [comment]
@whitef0x0 same here, someone knows what is happening?

**Comment by josx** [comment]
Here on code, https://github.com/tellform/tellform/search?utf8=%E2%9C%93&q=20523&type=
It is the port for using socket.io, so i think we can use another port running with the env var.

here use process.env.SOCKET_PORT 
https://github.com/tellform/tellform/blob/b29b0a9e8256c5107ad730d0524e51d3d26da93d/config/env/all.js

Here is hardcoded:
https://github.com/tellform/tellform/blob/d07c1c28ce37919699d69da75e73e733aa1df1a7/config/socket.io.js

**Comment by whitef0x0** [comment]
@leonardloo the recent merge should fix this
