### ISSUE TITLE
Handle question shortcuts if there are more than 9 choices.

### ISSUE THREAD

**Issue by muhfred** [tellform/tellform#216]
#### What's this issue about?

when answering a question of multiple choice question,  If there are more than 9 questions, the shortcut (10) doesn't work, cause the software thinks i pressed (1) first choice. Please handle this issue.

#### Expected behavior

a special keyboard shortcut is generated to choose an answer choice bigger than 9.
#### Actual behavior

when choosing a choice number 10 of a multiple choice question of 10 choices the keyboard shortcut (10) doesn't work.
#### Steps to reproduce

create a multiple choice question of more than 9 choices and answer the question choosing choice number 10 using the keyboard shortcut (10).
#### Environment

using the online app tellform.com
chrome: latest version
OS: windows 10.

**Comment by whitef0x0** [comment]
Hey muhfred. I'll look into this.

We might have to change from using numbers to letters in this case as its hard to differentiate between a user pressing 1 and 0 for 10 and pressing 1, then 0.
