### ISSUE TITLE
Delete field button disappears on admin.tellform.com

### ISSUE THREAD

**Issue by vr00n** [tellform/tellform#217]
#### What's this issue about?
Unable to delete fields.
![image](https://user-images.githubusercontent.com/4397663/29214086-f39ad660-7e73-11e7-9a1b-b6248006b0cd.png)

#### Expected behavior
The appearance of **Delete** buttons next individual field names.

See here for an example of a DELETE BUTTON next to a Question.
![image](https://user-images.githubusercontent.com/4397663/29232287-dda9bf3e-7eb8-11e7-80bc-29d1e9f0bfba.png)

#### Actual behavior
Delete buttons next individual field names disappeared after i added the 3rd field.

#### Steps to reproduce
I copied a field and then kept adding new fields and the delete button disappeared

#### Environment

Was using admin.tellform.com
MAC OSX Sierra - 10.12.6 (16G29)
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Seems related to #172 . My screen resolution is 1440 x 900

**Comment by whitef0x0** [comment]
I'll be getting to this. In the backlog right now.
