### ISSUE TITLE
Bulk add options for Dropdown field

### ISSUE THREAD

**Issue by vr00n** [tellform/tellform#218]
#### What's this issue about?

Would like to copy/paste options for inclusion into the dropdown and multiple-choice fields.

#### About the Feature
When adding a field with several possible options (`multiple-choice or dropdown`), it would be useful to copy/paste from a list of pre-existing choices.
So instead of constantly clickin on "add option" button as per below, would be include to have a bulk-add option that changes this to a paragraph input where user can input choices in comma-separated format. These then automatically become the field choices!

![image](https://user-images.githubusercontent.com/4397663/29232592-6a3f66be-7eba-11e7-8b19-279cd59d7ad8.png)

**Comment by whitef0x0** [comment]
@vr00n this is in the works

**Comment by vr00n** [comment]
@whitef0x0 great! proceed to close this?
