### ISSUE TITLE
Email in a restricted env / Disable email but allow signups

### ISSUE THREAD

**Issue by James9074** [tellform/tellform#220]
#### What's this issue about?

In a restricted environment, I can't access mail APIs, and thus can't use this application beyond a single admin account.

#### About the Feature

I'd like to see the ability to do signup without email confirmation, or the ability to use SMTP directly. That, or some way to integrate with an opensource mail api alternative that I an run internally, like Postal.

I'm also not sure what options are available for the MAILER_SERVICE_PROVIDER var. Of course I found out by looking at the code, but this should probably be a little more apparent in the readme.

**Comment by whitef0x0** [comment]
@James9074 updated the README with a link to valid MAILER_SERVICE_PROVIDER's. 

For your use case, PR's are always welcome.

**Comment by James9074** [comment]
Nice - I've got to add in custom service details for this anyways so I'll make sure to do a PR. Would you be okay with new env vars called `MAILER_SMTP_HOST` / `MAILER_SMTP_PORT` / etc? If they were detected I'd take those over the MAILER_SERVICE_PROVIDER and configure the connection manually [here](https://github.com/tellform/tellform/blob/4d4007436808fcff53acd24b256c0df4d3143381/app/models/user.server.model.js#L16).
