### ISSUE TITLE
deleting dist/ folder and running grunt build results in empty app

### ISSUE THREAD

**Issue by leonardloo** [tellform/tellform#222]
I realized `dist` is in `.gitignore` but you have a `dist` folder in your repo. When I delete the `dist` folder then re-run grunt build, then build and run the docker container, I get a completely blank page for my app, with no errors printed to the console.

Why is that the case?

**Comment by leonardloo** [comment]
Realised that the problem is due to `grunt build` failing at `closure-compiler` command, thus it doesn't rebuild the vendor files. Attempting to fix this, off the bat it seems java is not installed inside the Docker image.

**Comment by whitef0x0** [comment]
@leonardloo Sorry about that. I'll try to install java in the docker image first.

**Comment by whitef0x0** [comment]
This has been fixed.
