### ISSUE TITLE
Installation - default credentials?

### ISSUE THREAD

**Issue by SaMnCo** [tellform/tellform#236]
Hi team! 

#### What's this issue about?
I am deploying on Kubernetes using a quick and dirty Helm chart. I can get to the login page, logs are pretty good looking even if I lose Redis for a little while systematically. 
However, I cannot login. 

I am probably doing it wrong, or missing the point in the docs, but I cannot figure out what to do next. Any hint? 

#### Expected behavior
I was expecting the system to auto create a first user like it seems to do in crearte_admin.js (I have setup env for that) 

#### Actual behavior
Unable to login or create a user 

#### Steps to reproduce
the chart is really dirty, I just wanted to get going with TellForm, so I am hesitating to share crapeware. That being saidm below are all ENV I set: 

 ```
  APP_NAME: tellform
  APP_DESC: "Open Source alternative to TypeForm"
  SIGNUP_DISABLED: false
  DISABLE_CLUSTER_MODE: true
  SUBDOMAINS_DISABLED: false
  SESSION_SECRET: CHANGE_ME_PLEASE
  PORT: 3000
  SOCKET_PORT: 20523
  username: admin

  # Environment: 
  NODE_ENV: production

  # Create first user
  CREATE_ADMIN_ACCOUNT: true
  ADMIN_EMAIL: admin@admin.com
  ADMIN_USERNAME: root
  ADMIN_PASSWORD: password

  # Analytics
  GOOGLE_ANALYTICS_ID: {}
  PRERENDER_TOKEN: {}
  COVERALLS_REPO_TOKEN: {}
  DSN_KEY: {}
  RAVEN_DSN: {}
  reCAPTCHA_KEY: {}

  # Social Accounts
  FACEBOOK_ID: {}
  FACEBOOK_SECRET: {}

  TWITTER_KEY: {}
  TWITTER_SECRET: {}

  GOOGLE_ID: {}
  GOOGLE_SECRET: {} 

  LINKEDIN_ID: {}
  LINKEDIN_SECRET: {} 

  GITHUB_ID: {}
  GITHUB_SECRET: {} 

  # Mail config
  mail: 
    MAILER_EMAIL_ID: samnco@gmail.com
    MAILER_PASSWORD: XXXXXX
    MAILER_FROM: samnco@gmail.com

    # Use this for one of Nodemailer's pre-configured service providers
    MAILER_SERVICE_PROVIDER: Gmail

    # Use these for a custom service provider 
    # Note: MAILER_SMTP_HOST will override MAILER_SERVICE_PROVIDER
    MAILER_SMTP_HOST: smtp.gmail.com
    MAILER_SMTP_PORT: 465
    MAILER_SMTP_SECURE: true
```

#### Environment
Kubernetes 1.7.6 (GKE) on Ubuntu

Many thanks for your help.

**Comment by whitef0x0** [comment]
@SaMnCo First off, you can remove the "username" field from your .env file. Secondly what is the output.

Secondly your .env file should use "=" not "=". Thirdly, you don't want to have "{}" in your .env file as they won't be treated like JS Objects, but instead as plain strings. If you change your .env file to look like the code below it *should* work.

```
APP_NAME=tellform
 APP_DESC="Open Source alternative to TypeForm"
 SIGNUP_DISABLED=false
 DISABLE_CLUSTER_MODE=true
 SUBDOMAINS_DISABLED=false
 SESSION_SECRET=CHANGE_ME_PLEASE
 PORT=3000
 SOCKET_PORT=20523

 # Environment
 NODE_ENV=production

 # Create Admin User
 CREATE_ADMIN_ACCOUNT=TRUE
 ADMIN_EMAIL=admin@admin.com
 ADMIN_USERNAME=root
 ADMIN_PASSWORD=password

 # Mail config
MAILER_EMAIL_ID=samnco@gmail.com
MAILER_PASSWORD=XXXXXX
MAILER_FROM=samnco@gmail.com

# Use this for one of Nodemailer's pre-configured service providers MAILER_SERVICE_PROVIDER=Gmail
```

**Comment by SaMnCo** [comment]
Hello,

Thanks for coming back to me. Actually, this is not "literally" how I
configure it. What I shared is a yaml file I use to set the ENV in the
dockerfile, hence the : and {} for empty fields.

I will remove the username one and try it out again, but I suspect it won't
change much since it must be ignored already.

Not sure what you mean by "what is the output". Would you like a log trail?




On Oct 10, 2017 22:53, "David Baldwynn" <notifications@github.com> wrote:

@SaMnCo <https://github.com/samnco> First off, you can remove the
"username" field from your .env file. Secondly what is the output.

Secondly your .env file should use "=" not "=". Thirdly, you don't want to
have "{}" in your .env file as they won't be treated like JS Objects, but
instead as plain strings. If you change your .env file to look like the
code below it *should* work.

APP_NAME=tellform
 APP_DESC="Open Source alternative to TypeForm"
 SIGNUP_DISABLED=false
 DISABLE_CLUSTER_MODE=true
 SUBDOMAINS_DISABLED=false
 SESSION_SECRET=CHANGE_ME_PLEASE
 PORT=3000
 SOCKET_PORT=20523

 # Environment
 NODE_ENV=production

 # Create Admin User
 CREATE_ADMIN_ACCOUNT=TRUE
 ADMIN_EMAIL=admin@admin.com
 ADMIN_USERNAME=root
 ADMIN_PASSWORD=password

 # Mail config
MAILER_EMAIL_ID=samnco@gmail.com
MAILER_PASSWORD=XXXXXX
MAILER_FROM=samnco@gmail.com

# Use this for one of Nodemailer's pre-configured service providers
MAILER_SERVICE_PROVIDER=Gmail

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tellform/tellform/issues/236#issuecomment-335619607>,
or mute the thread

**Comment by whitef0x0** [comment]
@SaMnCo I fixed a bug related to this. If you pull the most recent master it should create an admin account. Yea can I see a log trail of some sort or at least the stdout?

**Comment by whitef0x0** [comment]
If you have a chance can you also run this in your mongoshell and give me the output?

```
db.users.find({$or: [{ "username": "root" }, { "username": "admin" }] });
```

**Comment by whitef0x0** [comment]
@SaMnCo did you end up getting this sorted?

**Comment by SaMnCo** [comment]
Sorry didn't have time, on my task list this week. I had a crazy bad
network connection, couldn't even upload my docker image :(

I'll keep you posted.

**Comment by SaMnCo** [comment]
OK just did a new deploy with your latest Dockerfile. I did a few changes as K8s does not like to create files at the root of a directory so I am converting the ENV variable into the .env at startup. 

From the logs perspective it seems to be OK. But I get a blank page and in the console: 

```
tellform.landg.madeden.net/:44 GET http://tellform.landg.madeden.net/static/lib/jquery-ui/themes/flick/jquery-ui.css net::ERR_ABORTED
tellform.landg.madeden.net/:70 GET http://tellform.landg.madeden.net/static/lib/file-saver.js/FileSaver.js net::ERR_ABORTED
tellform.landg.madeden.net/:43 GET http://tellform.landg.madeden.net/static/lib/angular-input-stars/angular-input-stars.css net::ERR_ABORTED
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
angular-strap.js:4338 Uncaught ReferenceError: angular is not defined
    at angular-strap.js:4338
    at angular-strap.js:4338
(anonymous) @ angular-strap.js:4338
(anonymous) @ angular-strap.js:4338
application.min.js:1 Uncaught ReferenceError: angular is not defined
    at application.min.js:1
(anonymous) @ application.min.js:1
```

Effectively, if I look into the code post deployment: 

```bash
$ kubectl exec -n tellform $(kubectl get pods -n tellform -l app=tellform -o name | cut -f2 -d/) -- find / -name jquery-ui.css
```
does not return anything. Is that normal?

**Comment by whitef0x0** [comment]
@SaMnCo I just made a docker-compose file you can use if you want that sets up nginx and tellform. If you don't go that route, I would look at the Dockerfile in the docker branch as thats the most recent Docker file that has been verified to work.

**Comment by SaMnCo** [comment]
@whitef0x0 can you check about your compose file? I can't find it in any branch. I found one in a very old commit but nothing more. 

Thanks

**Comment by whitef0x0** [comment]
@SaMnCo the compose file is in a separate repo (documentation for it will be added in the 2.20 release) here github.com/tellform/docker_files

**Comment by fyudelgado** [comment]
I was trying to run the tellform using docker, I used the configuration .env file that you provide on this thread, but the log file for tellform service is sending this error message:

Your mail configuration is incorrect: Error: Invalid login: 534-5.7.9 Application-specific password required. Learn more at 534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor b44-v6sm10826387edd.93 - gsmtp

My gmail credentials are verified and working on other applications, also sign in on the www.gmail.com site.

Mi configuration file is:

# Set this to the path where Mailu data and configuration is stored
ROOT=/opt/tellform_data

APP_NAME=tellform
APP_DESC="Fivetek TypeForm"
SIGNUP_DISABLED=false
DISABLE_CLUSTER_MODE=true
SUBDOMAINS_DISABLED=false
SESSION_SECRET=ChangeMeChangeMe
PORT=3000
SOCKET_PORT=20523

# URI of Mongo database that TellForm will connect to
MONGODB_URI=mongodb://mongo/tellform

# URL Redis server that TellForm will connect to
REDIS_URL=redis://redis:6379

# Environment
NODE_ENV=production

# Create Admin User
CREATE_ADMIN_ACCOUNT=TRUE
ADMIN_EMAIL=admin@admin.com
ADMIN_USERNAME=root
ADMIN_PASSWORD=password

# Mail config
MAILER_EMAIL_ID=fyudelgado@gmail.com
MAILER_PASSWORD=XXXXXXXXXXX
MAILER_FROM=fyudelgado@gmail.com

# Use this for one of Nodemailer's pre-configured service providers
MAILER_SERVICE_PROVIDER=Gmail

What are I'm doing wrong?

Regards,
