### ISSUE TITLE
Angular Material with Tellform

### ISSUE THREAD

**Issue by tvvignesh** [tellform/tellform#238]
I am looking to implement tellform using angular material (https://material.angularjs.org/latest/) 

What portions of the project will I need to change to move from bootstrap to material? 

Thanks in advance.

**Comment by whitef0x0** [comment]
@tvvignesh this will be pretty hard to do as we use bootstrap and bootstrap components just about everywhere.

**Comment by tvvignesh** [comment]
@whitef0x0 My boss is pretty determined to do it and no is not going to be an answer for him. So, just in case I have to do it, will I have to redesign the entire UI with new tags all over again? If yes, what will happen to the libraries you use? Does it depend on bootstrap?

Sorry for bothering you. Just a poor developer out here :-(

**Comment by whitef0x0** [comment]
@tvvignesh probably easier to just add a css to "style" it in the Material style then actually remove bootstrap.

**Comment by tvvignesh** [comment]
@whitef0x0 Tried that. Its breaking a lot and our existing project uses material. Never mind. Sorry to bother you. Will try it out and if any luck, will let you know. Have to complete it this week btw.
