### ISSUE TITLE
Editing and saving a field makes it duplicated

### ISSUE THREAD

**Issue by alexgleason** [tellform/tellform#239]
Tested on FireFox and Chromium.

1. Edit a field
2. Click save
3. The field now also displays at the very bottom

Here's an example. I edited "ayy" and clicked save. Now it also appears at the very bottom.
![screenshot from 2017-10-17 12 51 48](https://user-images.githubusercontent.com/3639540/31677814-fac02436-b339-11e7-9ccd-183ec8c3f073.png)

**Comment by alexgleason** [comment]
I'm getting this in my console:

>Error: [ngRepeat:dupes] https://docs.angularjs.org/error/ngRepeat/dupes?p0=jump_field%20in%20myform.form_fields&p1=object:187&p2=%7B%22fieldValue%22:%22Regular%20member%22,%22globalId%22:%22PaS5VT0ojUW6TZUk241iM2I42BfLvsmArrJq62ToSTu%22,%22lastModified%22:%222017-10-17T16:43:45.219Z%22,%22title%22:%22What%20type%20of%20person%20are%20you%3F%22,%22fieldType%22:%22radio%22,%22logicJump%22:%7B%22jumpTo%22:%2259e632f2487aadcd65bfcef6%22,%22expressionString%22:%22field%20%3D%3D%20static%22,%22valueB%22:%22Spouse%22,%22_id%22:%2259e632e1487aadcd65bfcef4%22,%22id%22:%2259e632e1487aadcd65bfcef4%22%7D,%22_id%22:%2259e632e1487aadcd65bfcef0%22,%22created%22:%222017-10-17T16:42:09.071Z%22,%22validFieldTypes%22:%5B%22textfield%22,%22date%22,%22email%22,%22link%22,%22legal%22,%22url%22,%22textarea%22,%22statement%22,%22welcome%22,%22thankyou%22,%22file%22,%22dropdown%22,%22scale%22,%22rating%22,%22radio%22,%22checkbox%22,%22hidden%22,%22yes_no%22,%22natural%22,%22stripe%22,%22number%22%5D,%22deletePreserved%22:false,%22disabled%22:false,%22required%22:true,%22fieldOptions%22:%5B%7B%22option_id%22:49814,%22option_title%22:%22Option%200%22,%22option_value%22:%22Council%20member%22,%22_id%22:%2259e632e1487aadcd65bfcef3%22,%22$$hashKey%22:%22object:167%22%7D,%7B%22option_id%22:11841,%22option_title%22:%22Option%202%22,%22option_value%22:%22Regular%20member%22,%22_id%22:%2259e632e1487aadcd65bfcef2%22,%22$$hashKey%22:%22object:168%22%7D,%7B%22option_id%22:54763,%22option_title%22:%22Option%203%22,%22option_value%22:%22Spouse%22,%22_id%22:%2259e632e1487aadcd65bfcef1%22,%22$$hashKey%22:%22object:169%22%7D%5D,%22description%22:%22%22,%22isSubmission%22:false,%22$$hashKey%22:%22object:187%22%7D

**Comment by whitef0x0** [comment]
This has been fixed as well.
