### ISSUE TITLE
Logic Jump is not reflected in UI after saving

### ISSUE THREAD

**Issue by alexgleason** [tellform/tellform#241]
1. Configure a logic jump
2. It works!
3. Edit the form field
4. The logic jump is not displayed
5. It continues to work

From what I can tell, the functionality works. But when you go to edit a form element it doesn't display the logic jump.

Here's a form with a logic jump that's working, but not displayed:

![screenshot from 2017-10-17 13 01 01](https://user-images.githubusercontent.com/3639540/31678170-432448a0-b33b-11e7-9930-b514588ea823.png)

It might be helpful to also include something within the element list signifying that a logic jump is enabled on that element.

**Comment by whitef0x0** [comment]
This has been fixed. I'll look into adding an icon or something that a logic jump is active in a week or two.
