### ISSUE TITLE
Checkbox field requires

### ISSUE THREAD

**Issue by modiplus91** [tellform/tellform#244]
#### What's this issue about?

For a multiple choice option checkbox is mandatory. How to implement checkbox in this repo. 

#### Expected behavior
Currently in multiple choice option it is only radio button to select one. this work can be done by dropdown also but is a qustion is been asked for muliple choices then ? 
For this in Multiple choice only we can give a button to choose multiple or single. if opted for multiple then checkbox will open. 

* Please state functionality change that is required so that we can contribute in this feature.

**Comment by whitef0x0** [comment]
@modiplus91 to implement a checkbox field, you'll need to add a fieldType to the validFieldTypes array in app/libs/constants.js and add a field template to public/form_modules/views/directiveViews/fields/

**Comment by pranavm27** [comment]
@modiplus91 you also need to make an entry in [form-fields.client.service.js](https://github.com/tellform/tellform/blob/master/public/modules/forms/admin/services/form-fields.client.service.js)

**Comment by whitef0x0** [comment]
Closing as this is a duplicate of https://github.com/tellform/tellform/issues/106
