### ISSUE TITLE
Grunt Build failing

### ISSUE THREAD

**Issue by ajinkyagadewar** [tellform/tellform#302]
#### What's this issue about?
Grunt build is failing.

grunt build
Running "jshint:all" (jshint) task

   public/form_modules/forms/base/config/i18n/swedish.js
      1 |+'use strict';
          ^ Expected an assignment or function call and instead saw an expression.
      3 |+angular.module('view-form').config(['$translateProvider', function ($translateProvider) {
         ^ Confusing plusses.
      4 |+
         ^ Missing "use strict" statement.
      5 |+  $translateProvider.translations('en', {
         ^ Confusing plusses.
      6 |+    FORM_SUCCESS: 'Formulärsvaret skickades framgångsrikt in!',
         ^ Expected '}' to match '{' from line 5 and instead saw '+'.
      6 |+    FORM_SUCCESS: 'Formulärsvaret skickades framgångsrikt in!',
              ^ Expected ')' and instead saw 'FORM_SUCCESS'.
      6 |+    FORM_SUCCESS: 'Formulärsvaret skickades framgångsrikt in!',
              ^ Expected an assignment or function call and instead saw an expression.
      6 |+    FORM_SUCCESS: 'Formulärsvaret skickades framgångsrikt in!',
                          ^ Missing semicolon.
      6 |+    FORM_SUCCESS: 'Formulärsvaret skickades framgångsrikt in!',
                          ^ Expected '}' to match '{' from line 3 and instead saw ':'.
      6 |+    FORM_SUCCESS: 'Formulärsvaret skickades framgångsrikt in!',
                            ^ Expected ']' to match '[' from line 3 and instead saw 'Formulärsvaret skickades framgångsrikt in!'.
      7 |+    REVIEW: 'Granska',
                    ^ Expected ')' and instead saw ':'.
      7 |+    REVIEW: 'Granska',
                    ^ Expected an assignment or function call and instead saw an expression.
      7 |+    REVIEW: 'Granska',
                     ^ Missing semicolon.
      8 |+    BACK_TO_FORM: 'Gå tillbaka till Formuläret',
              ^ Expected an assignment or function call and instead saw an expression.
      8 |+    BACK_TO_FORM: 'Gå tillbaka till Formuläret',
                          ^ Missing semicolon.

#### Expected behavior
Successfully build an app

#### Actual behavior
Errors. error: couldn't process source due to parse error

#### Steps to reproduce
grunt build

#### Environment
OS: Mac HighSierra
npm: 5.6.0

**Comment by pshah123** [comment]
This is really late but this is due to the entire file being diffed for some reason. Remove the "+ " at the beginning of each line (you can do this quickly with a search and replace regex)

**Comment by ajinkyagadewar** [comment]
Thanks @pshah123 I did that and got it working
