### ISSUE TITLE
Not able to delete entries from form

### ISSUE THREAD

**Issue by LukasSchulz** [tellform/tellform#315]
#### What's this issue about?

I am not able to delete entries at the analyze page of tellform. Furthermore, the stats aren't updated.

#### Expected behavior

Entries get deleted when I click on the button "delete selected".
#### Actual behavior

After reloading the page, the Items that seemed to be deleted reappear.
#### Steps to reproduce

Try to delete entries of a form.
#### Environment

Account on the admin.tellform.com website; Windows 10; Chrome and Firefox (tried both)

**Comment by LoneRifle** [comment]
I'm not sure if the code found at f369a4e would be useful (this is from the FormSG fork), but I can reproduce the problem. Assuming that I can get this to work on my local machine, I'll be happy to put in a PR
