### ISSUE TITLE
Example server SSL certificate has expired.

### ISSUE THREAD

**Issue by tmikaeld** [tellform/tellform#327]
The certificate has expired.

**Comment by gtsatsis** [comment]
@busyML, The certificate can be renewed through one command on the backend of the example server.

I suggest tagging the lead Developer of the project. (@whitef0x0 (?)).

**Comment by busyML** [comment]
Right, thanks a lot @gtsatsis. @whitef0x0 , anything we can do to help with this? The expired SSL means that embedded forms are not loading properly, so it is quite an urgent matter.

**Comment by Luc45** [comment]
Yep, came here to say I went to see the demos but couldn't because of expired SSL certificate: https://example.tellform.com/#!/forms/598cbfdebc19076a1dc78f23

**Comment by busyML** [comment]
@Luc45 , yes, I mean you can still access the form, however most browsers will just try to stop you because they think the website isn´t safe, however it is, if you click through the security warnings, you´ll get to the demo

**Comment by busyML** [comment]
@Luc45 Yes, agree, the problem is affecting all forms and it makes any created forms usuable on the front-end. I had to switch to **Typeform** for my website, whose free version is more limited than tellform, unfortunately. However it doesn´t seem like we can do much until they renew the certificate on the tellform back end.

**Comment by Ryonez** [comment]
> yes, I mean you can still access the form, however most browsers will just try to stop you because they think the website isn´t safe, however it is, if you click through the security warnings, you´ll get to the demo.

Actually as @Luc45 mentioned Chrome will straight up just block you.

![image](https://user-images.githubusercontent.com/16157130/52915200-d452f300-3335-11e9-9ff1-70d8c634445c.png)

@James9074 @whitef0x0 One of you guys should really get this sorted, it's such a simple fix, and the process to renew letencrypt certs can even be automated. Not taking into consideration this is what new people see when trying to check this out, it's a bad look.

**Comment by instanteach** [comment]
@Ryonez Couldn't agree more with you, however none of the backend devs have been answering us

**Comment by whitef0x0** [comment]
Hey all! I'll get this sorted this week

**Comment by busyML** [comment]
@whitef0x0 , thank you !

**Comment by gnowland** [comment]
Is this project even still in active development, if the SSL certificate has been expired for 3 months and it takes 1 CLI command to renew? 🤯

Hell, you can even make a cron job to renew it automatically :
```
0  13  *  *  *  ec2-user  /opt/letsencrypt/letsencrypt-auto
```
* Don't forget to add a cron job to automatically restart your server (apache, nginx, etc) after the certificate has been renewed or it will not be loaded

**Comment by tobya** [comment]
If it is possible for you to run [CaddyServer](https://github.com/mholt/caddy), it will renew LetsEncrypt certs for you automagically.  You can use it as a forward proxy and dont need to change your setup.

**Comment by dromer** [comment]
Even the contact-form uses the example domain. This is quite annoying.
How am I supposed to convince my colleagues that we should try this software if I can't show any examples? ;)

**Comment by kolaente** [comment]
Any updates on this?

**Comment by whitef0x0** [comment]
@kolaente @dromer certs have been updated and moved to letsencrypt. I'll be getting the example server up by end of today. Sorry about the lack of communication, been busy with the last year of school!
